### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by zengargoyle** [hatena/Test-Time-At#1]
missing a testing dependency for DateTime.

~/.cpanm/work/1441335644.21515/Test-Time-At-0.01$ ./Build test
t/00_compile.t ..... ok  
t/base.t ........... Can't locate DateTime.pm in @INC (you may need to install the DateTime module) ...

**Comment by shibayu36** [comment]
I wrote that "DateTime" is required on develop,  so it is not needed for test.  But I forgot to remove "use DateTime" in t/base.t...

I fixed it by https://github.com/hatena/Test-Time-At/pull/2 and soon I'll release version 0.0.2.

Thanks for your report!

**Comment by shibayu36** [comment]
I just now released!
